name: AutoItemBarReload
main: net.Dockter.HotBarReload.AutoItemBarReload
version: 1.0
author: Dockter
description: >
             Automatically reloads an item on the item bar with a matching stack in the player's inventory.
permissions:
  autoitembarreload.disallow:
    description: Denies access to AutoItemBarReload.
    default: false